name: Generate Pacman Contribution Graph

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move SVG to /output directory
        run: |
          mkdir -p output
          mv dist/pacman-contribution-graph.svg output/pacman.svg

      - name: Commit and push to main branch
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/pacman.svg'
          message: 'chore: update pacman contribution graph'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
